spring.application.name=company-tender-review
# # H2 内存数据库
# spring.datasource.url=${DB_URL:jdbc:h2:mem:company_tender_review;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false}
# spring.datasource.username=${DB_USERNAME:sa}
# spring.datasource.password=${DB_PASSWORD:}
# spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
# spring.sql.init.mode=${SQL_INIT_MODE:never}

# MySQL 数据库
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/company_tender_review}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}
spring.sql.init.mode=${SQL_INIT_MODE:never}


app.auth.jwt.secret=${JWT_SECRET:0123456789abcdef0123456789abcdef}
app.auth.jwt.access-expire-seconds=7200
app.auth.jwt.refresh-expire-seconds=604800

# logging.level.root=DEBUG